# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radio.ui'
#
# Created: Mon Mar  3 02:51:46 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import QWidget
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(725, 432)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(20, 370, 151, 32))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.stereoWidthSlider = QtGui.QSlider(self.centralwidget)
        self.stereoWidthSlider.setGeometry(QtCore.QRect(100, 300, 81, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stereoWidthSlider.sizePolicy().hasHeightForWidth())
        self.stereoWidthSlider.setSizePolicy(sizePolicy)
        self.stereoWidthSlider.setMaximum(100)
        self.stereoWidthSlider.setProperty("value", 50)
        self.stereoWidthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.stereoWidthSlider.setObjectName(_fromUtf8("stereoWidthSlider"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.freqSelect = QtGui.QDial(self.centralwidget)
        self.freqSelect.setGeometry(QtCore.QRect(-10, 50, 201, 151))
        self.freqSelect.setAutoFillBackground(False)
        self.freqSelect.setMinimum(881)
        self.freqSelect.setMaximum(1079)
        self.freqSelect.setSingleStep(2)
        self.freqSelect.setSliderPosition(907)
        self.freqSelect.setOrientation(QtCore.Qt.Horizontal)
        self.freqSelect.setInvertedAppearance(False)
        self.freqSelect.setWrapping(False)
        self.freqSelect.setNotchTarget(6.7)
        self.freqSelect.setNotchesVisible(True)
        self.freqSelect.setObjectName(_fromUtf8("freqSelect"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 56, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.curFreq = QtGui.QLabel(self.centralwidget)
        self.curFreq.setGeometry(QtCore.QRect(40, 210, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(18)
        font.setItalic(True)
        self.curFreq.setFont(font)
        self.curFreq.setObjectName(_fromUtf8("curFreq"))
#
#         self.spectrumPlot = Qwt5.QwtPlot(self.centralwidget)
#         self.spectrumPlot.setGeometry(QtCore.QRect(170, 40, 431, 200))
#         self.spectrumPlot.setAxisAutoScale(1)
#         self.spectrumPlot.setAutoReplot(1)
#         self.spectrumPlot.setObjectName(_fromUtf8("spectrumPlot"))

# central frame for plotting waveforms and spectra
        self.plotFrame = QWidget(self.centralwidget)
        self.plotFrame.setGeometry(QtCore.QRect(170, 40, 431, 200))
        self.plotFrame.setObjectName(_fromUtf8("plotFrame"))



        self.signalMeter = Qwt5.QwtThermo(self.centralwidget)
        self.signalMeter.setGeometry(QtCore.QRect(640, 50, 51, 181))
        self.signalMeter.setAlarmEnabled(False)
        self.signalMeter.setFillColor(QtGui.QColor(51, 114, 193))
        self.signalMeter.setMaxValue(0.0)
        self.signalMeter.setMinValue(-40.0)
        self.signalMeter.setProperty("value", -35.0)
        self.signalMeter.setObjectName(_fromUtf8("signalMeter"))
        self.signalMeter.setScalePosition(2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(575, 10, 121, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 280, 85, 18))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 270, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))

        self.drawSpectrum = QtGui.QCheckBox(self.centralwidget)
        self.drawSpectrum.setGeometry(QtCore.QRect(290,20,85,18))
        self.drawSpectrum.setObjectName(_fromUtf8("drawSpectrum"))
        self.spectrum_overall = QtGui.QRadioButton(self.centralwidget)
        self.spectrum_overall.setGeometry(QtCore.QRect(220, 240, 97, 18))
        self.spectrum_overall.setChecked(True)
        self.spectrum_overall.setObjectName(_fromUtf8("spectrum_overall"))
        self.spectrum_channel = QtGui.QRadioButton(self.centralwidget)
        self.spectrum_channel.setGeometry(QtCore.QRect(330, 240, 97, 18))
        #self.spectrum_channel.setEnabled(0)
        self.spectrum_channel.setObjectName(_fromUtf8("spectrum_channel"))
        self.spectrum_playing = QtGui.QRadioButton(self.centralwidget)
        self.spectrum_playing.setGeometry(QtCore.QRect(440, 240, 97, 18))
        #self.spectrum_playing.setEnabled(0)
        self.spectrum_playing.setObjectName(_fromUtf8("spectrum_playing"))
        self.spectrum_waveform = QtGui.QRadioButton(self.centralwidget)
        self.spectrum_waveform.setGeometry(QtCore.QRect(520, 240, 97, 18))
        #self.spectrum_waveform.setEnabled(0)
        self.spectrum_waveform.setObjectName(_fromUtf8("spectrum_waveform"))
        self.basechannel = QtGui.QCheckBox(self.centralwidget)
        self.basechannel.setGeometry(QtCore.QRect(20, 340, 85, 18))
        self.basechannel.setObjectName(_fromUtf8("mainchannel"))

        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(190, 270, 521, 131))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.demodfilt = QtGui.QWidget()
        self.demodfilt.setObjectName(_fromUtf8("demodfilt"))
        self.demodFilterSize = QtGui.QSlider(self.demodfilt)
        self.demodFilterSize.setGeometry(QtCore.QRect(170, 50, 160, 22))
        self.demodFilterSize.setMinimum(1)
        self.demodFilterSize.setMaximum(51)
        self.demodFilterSize.setSingleStep(2)
        self.demodFilterSize.setProperty("value", 11)
        self.demodFilterSize.setOrientation(QtCore.Qt.Horizontal)
        self.demodFilterSize.setTickPosition(QtGui.QSlider.TicksBelow)
        self.demodFilterSize.setTickInterval(5)
        self.demodFilterSize.setObjectName(_fromUtf8("demodFilterSize"))
        self.label_6 = QtGui.QLabel(self.demodfilt)
        self.label_6.setGeometry(QtCore.QRect(170, 30, 56, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.demodFiltSizeLabel = QtGui.QLabel(self.demodfilt)
        self.demodFiltSizeLabel.setGeometry(QtCore.QRect(210, 30, 56, 13))
        self.demodFiltSizeLabel.setObjectName(_fromUtf8("demodFiltSizeLabel"))
        self.demodFiltMedian = QtGui.QRadioButton(self.demodfilt)
        self.demodFiltMedian.setGeometry(QtCore.QRect(20, 10, 97, 18))
        self.demodFiltMedian.setChecked(True)
        self.demodFiltMedian.setObjectName(_fromUtf8("demodFiltMedian"))
        self.demodFiltLP = QtGui.QRadioButton(self.demodfilt)
        self.demodFiltLP.setGeometry(QtCore.QRect(20, 50, 97, 18))
        self.demodFiltLP.setObjectName(_fromUtf8("demodFiltLP"))
        self.tabWidget.addTab(self.demodfilt, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.audioFilterSizeSlider = QtGui.QSlider(self.tab)
        self.audioFilterSizeSlider.setGeometry(QtCore.QRect(180, 50, 160, 22))
        self.audioFilterSizeSlider.setAutoFillBackground(False)
        self.audioFilterSizeSlider.setMinimum(1)
        self.audioFilterSizeSlider.setMaximum(24)
        self.audioFilterSizeSlider.setProperty("value", 8)
        self.audioFilterSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.audioFilterSizeSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.audioFilterSizeSlider.setTickInterval(2)
        self.audioFilterSizeSlider.setObjectName(_fromUtf8("audioFilterSizeSlider"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(180, 20, 56, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.audioFilterSizeText = QtGui.QLabel(self.tab)
        self.audioFilterSizeText.setGeometry(QtCore.QRect(230, 20, 56, 13))
        self.audioFilterSizeText.setObjectName(_fromUtf8("audioFilterSizeText"))
        self.audioFilterActive = QtGui.QCheckBox(self.tab)
        self.audioFilterActive.setGeometry(QtCore.QRect(40, 20, 85, 18))
        self.audioFilterActive.setChecked(True)
        self.audioFilterActive.setObjectName(_fromUtf8("audioFilterActive"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        # self.actionSetFreq = QtGui.QAction(MainWindow)
        #  self.actionSetFreq.setObjectName(_fromUtf8("actionSetFreq"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.audioFilterSizeSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.audioFilterSizeText.setNum)
        QtCore.QObject.connect(self.demodFilterSize, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.demodFiltSizeLabel.setNum)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.exitButton.setText(_translate("MainWindow", "Quit", None))
        self.label.setText(_translate("MainWindow", "Frequency Selection", None))
        self.label_2.setText(_translate("MainWindow", "Spectrum", None))
        self.curFreq.setText(_translate("MainWindow", "90.7 MHz", None))
        self.label_3.setText(_translate("MainWindow", "Signal Strength - dB", None))
        self.checkBox.setText(_translate("MainWindow", "Stereo", None))
        self.label_4.setText(_translate("MainWindow", "Stereo Width", None))
        self.drawSpectrum.setText(_translate("MainWindow", "Draw", None))
        self.spectrum_overall.setText(_translate("MainWindow", "Overall", None))
        self.spectrum_channel.setText(_translate("MainWindow", "Channel", None))
        self.spectrum_playing.setText(_translate("MainWindow", "Playing", None))
        self.spectrum_waveform.setText(_translate("MainWindow", "Waveform", None))
        self.multicore.setText(_translate("MainWindow", "Multicore", None))
        self.label_6.setText(_translate("MainWindow", "Size:", None))
        self.demodFiltSizeLabel.setText(_translate("MainWindow", "11", None))
        self.demodFiltMedian.setText(_translate("MainWindow", "Median", None))
        self.demodFiltLP.setText(_translate("MainWindow", "Lowpass", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.demodfilt), _translate("MainWindow", "Demodulation Filter", None))
        self.label_5.setText(_translate("MainWindow", "Width:", None))
        self.audioFilterSizeText.setText(_translate("MainWindow", "8", None))
        self.audioFilterActive.setText(_translate("MainWindow", "On", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Audio Filter", None))
        self.actionSetFreq.setText(_translate("MainWindow", "setFreq", None))

from PyQt4 import Qwt5
